# Generated by Django 3.2.4 on 2023-03-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PtClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='工点名称')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, 'YS')], default=0, verbose_name='管段类型')),
               #('age', models.CharField(max_length=15, verbose_name='患者年龄')),
                ('file', models.FileField(upload_to='static/ptclass_file/', verbose_name='缺陷数据文件')),
                ('state', models.IntegerField(choices=[(0, '未知'), (1, '立即修复'), (2, '尽快修复'), (3, '无需修复')],
                                              default=0, editable=False, verbose_name='修复类型')),
                ('diagnosis', models.TextField(default='暂无', editable=False, verbose_name='修复建议')),
                ('schema', models.TextField(default='暂无', editable=False, verbose_name='养护建议')),
            ],
            options={
                'verbose_name': '智慧方案',
                'verbose_name_plural': '修复建议',
                'db_table': 'patient_class',
            },
        ),
    ]
