# Generated by Django 3.2.4 on 2023-04-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptclass', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='ptclass',
        #     name='age',
        #     field=models.CharField(help_text='请输入患者年龄', max_length=15, verbose_name='患者年龄'),
        # ),
        migrations.AlterField(
            model_name='ptclass',
            name='diagnosis',
            field=models.TextField(default='暂无', editable=False, help_text='初步判断结果', verbose_name='修复建议'),
        ),
        migrations.AlterField(
            model_name='ptclass',
            name='file',
            field=models.FileField(help_text='请上传该管道的缺陷数据文件', upload_to='static/ptclass_file/', verbose_name='病例文件'),
        ),
        migrations.AlterField(
            model_name='ptclass',
            name='gender',
            field=models.IntegerField(choices=[(0, '未知'), (1, 'YS')], default=0, help_text='请选择管段类型', verbose_name='管段类型'),
        ),
        migrations.AlterField(
            model_name='ptclass',
            name='name',
            field=models.CharField(db_index=True, help_text='请输入工点名称', max_length=128, verbose_name='工点名称'),
        ),
        migrations.AlterField(
            model_name='ptclass',
            name='state',
            field=models.IntegerField(choices=[(0, '未知'), (1, '立即修复'), (2, '尽快修复'), (3, '无需修复')], default=0, editable=False, help_text='初步分类结果', verbose_name='分型'),
        ),
    ]
