# Generated by Django 3.2.4 on 2025-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptclass', '0002_auto_20230401_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptclass',
            name='file',
        ),
        migrations.RemoveField(
            model_name='ptclass',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ptclass',
            name='schema',
        ),
        migrations.AddField(
            model_name='ptclass',
            name='defect_density',
            field=models.TextField(default='', help_text='请输入缺陷描述', verbose_name='缺陷描述'),
        ),
        migrations.AddField(
            model_name='ptclass',
            name='defect_type',
            field=models.IntegerField(choices=[(0, '未知'), (1, '沉积'), (2, '错口'), (3, '破裂')], default=0, help_text='请选择缺陷类型', verbose_name='缺陷类型'),
        ),
        migrations.AddField(
            model_name='ptclass',
            name='image',
            field=models.ImageField(blank=True, default='', help_text='上传管段录相关缺陷图像', null=True, upload_to='static/ptclass_file/', verbose_name='缺陷图像'),
        ),
        migrations.AlterField(
            model_name='ptclass',
            name='diagnosis',
            field=models.TextField(default='暂无', help_text='此处为初步建议结果，若需补充可在此备注', verbose_name='修复建议'),
        ),
        migrations.AlterField(
            model_name='ptclass',
            name='state',
            field=models.IntegerField(choices=[(0, '无需修复'), (1, '立即修复'), (2, '尽快修复'), (3, '未知')], default=0, help_text='初步建议结果', verbose_name='修复类型'),
        ),
    ]
