# Generated by Django 3.2.4 on 2023-03-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgseg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='state',
            field=models.IntegerField(choices=[(0, '待处理'), (1, '已处理')], default=0, editable=False, verbose_name='状态'),
        ),

    ]
