# Generated by Django 3.2.4 on 2023-04-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgseg', '0003_auto_20230401_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tips',
            field=models.TextField(default='暂无', help_text='若判断有误可在此处添加备注', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='image',
            name='state',
            field=models.IntegerField(choices=[(0, '待处理'), (1, '已处理'), (2, '处理有误')], default=0, editable=False, verbose_name='状态'),
        ),
    ]
