# Generated by Django 3.2.4 on 2025-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgseg', '0004_auto_20230403_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(help_text='工点名称', max_length=15, verbose_name='工点名称'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tips',
            field=models.TextField(default='暂无', help_text='若处理有误可在此处添加备注', verbose_name='备注'),
        ),
    ]
