# Generated by Django 3.2.4 on 2023-04-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morder',
            name='name',
            field=models.CharField(db_index=True, max_length=25, verbose_name='患者姓名'),
        ),
        migrations.AlterField(
            model_name='morder',
            name='pno',
            field=models.CharField(db_index=True, help_text='患者的住院号应该唯一', max_length=25, unique=True, verbose_name='住院号'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pno',
            field=models.CharField(db_index=True, help_text='患者的住院号应该唯一', max_length=25, unique=True, verbose_name='住院号'),
        ),
        migrations.DeleteModel(
            name='Pno',
        ),
    ]
