# Generated by Django 3.2.4 on 2023-04-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrecord', '0002_auto_20230401_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morder',
            name='imgmo1',
            field=models.ImageField(blank=True, null=True, upload_to='static/morder/', verbose_name='临时医嘱'),
        ),
        migrations.AlterField(
            model_name='morder',
            name='imgmo2',
            field=models.ImageField(blank=True, null=True, upload_to='static/morder/', verbose_name='长期医嘱'),
        ),
    ]
