# Generated by Django 3.2.4 on 2023-04-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrecord', '0004_auto_20230403_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admission_diagnosis',
            field=models.TextField(blank=True, default='暂无结果', help_text='检查后生成该项数据', max_length=40, null=True, verbose_name='入院诊断'),
        ),
        migrations.AddField(
            model_name='patient',
            name='aided_examination',
            field=models.TextField(blank=True, default='暂无数据', help_text='请在检查后导入该项数据', max_length=40, null=True, verbose_name='辅助检查'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.TextField(blank=True, default='暂无数据', help_text='请在检查后导入该项数据', null=True, verbose_name='血压(mmhg)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='breathe',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='请在检查后导入该项数据', null=True, verbose_name='呼吸(次/分)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='chief_complaint',
            field=models.TextField(blank=True, default='暂无', max_length=400, null=True, verbose_name='主诉'),
        ),
        migrations.AddField(
            model_name='patient',
            name='other',
            field=models.TextField(blank=True, default='暂无', null=True, verbose_name='其他'),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_history',
            field=models.TextField(blank=True, default='暂无', max_length=400, null=True, verbose_name='既往病史'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pulse',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='请在检查后导入该项数据', null=True, verbose_name='脉搏(次/分)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='spo2',
            field=models.TextField(blank=True, default='暂无数据', help_text='请在检查后导入该项数据', null=True, verbose_name='血氧饱和度(%)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='temperature',
            field=models.FloatField(blank=True, default=0, help_text='请在检查后导入该项数据', null=True, verbose_name='体温(℃)'),
        ),
    ]
