# Generated by Django 3.2.4 on 2025-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrecord', '0005_auto_20230403_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', help_text='请输入工点名称', max_length=128, verbose_name='工点名称')),
                ('image', models.ImageField(blank=True, default='', help_text='上传缺陷记录记录相关缺陷图像', null=True, upload_to='static/ptclass_file/', verbose_name='缺陷图像')),
                ('before_text', models.TextField(blank=True, default='', help_text='缺陷记录，包含描述及缺陷图像', null=True, verbose_name='相关描述')),
            ],
            options={
                'verbose_name': '缺陷记录',
                'verbose_name_plural': '缺陷记录',
                'db_table': 'patient_record',
            },
        ),
        migrations.DeleteModel(
            name='Morder',
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': '管段信息', 'verbose_name_plural': '管段信息'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='admission_diagnosis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='aided_examination',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='breathe',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='chief_complaint',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='other',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='past_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pno',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='spo2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='temperature',
        ),
        migrations.AddField(
            model_name='patient',
            name='defect_code',
            field=models.CharField(default='', help_text='请输入缺陷代码', max_length=25, verbose_name='缺陷代码'),
        ),
        migrations.AddField(
            model_name='patient',
            name='defect_density',
            field=models.CharField(default='', help_text='请输入缺陷描述', max_length=50, verbose_name='缺陷描述'),
        ),
        migrations.AddField(
            model_name='patient',
            name='defect_image',
            field=models.ImageField(blank=True, help_text='请上传缺陷的图片', null=True, upload_to='static/icon/', verbose_name='缺陷图片'),
        ),
        migrations.AddField(
            model_name='patient',
            name='defect_name',
            field=models.CharField(default='', help_text='请输入缺陷名称', max_length=50, verbose_name='缺陷名称'),
        ),
        migrations.AddField(
            model_name='patient',
            name='defect_type',
            field=models.IntegerField(choices=[(1, '结构性'), (2, '功能性')], default=1, help_text='请选择缺陷类型', verbose_name='缺陷类型'),
        ),
        migrations.AddField(
            model_name='patient',
            name='diameter',
            field=models.FloatField(default=300, help_text='请输入管段直径', verbose_name='管段直径mm'),
        ),
        migrations.AddField(
            model_name='patient',
            name='length',
            field=models.FloatField(default=0, help_text='请输入管段长度', verbose_name='管段长度m'),
        ),
        migrations.AddField(
            model_name='patient',
            name='material',
            field=models.IntegerField(choices=[(1, '塑料管'), (2, '混凝土管')], default=1, help_text='请选择管段材质', verbose_name='管段材质'),
        ),
        migrations.AddField(
            model_name='patient',
            name='segment_type',
            field=models.CharField(db_index=True, default='排水管道', max_length=25, verbose_name='管段类型'),
        ),
        migrations.AddField(
            model_name='patient',
            name='serial_number',
            field=models.CharField(db_index=True, default='0000', help_text='序号应该唯一', max_length=25, unique=True, verbose_name='序号'),
        ),
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
    ]
