"""
Django settings for simpleui_demo project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

from django.conf.urls.static import static

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&%up9@!s_$$4(qurnori=vit2#kg!bzs$_+m64^j$2-vzibx&p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', ]

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admindocs',
    # 注册自己的app
    # 3缺陷分类
    'imgclass',
    # 1智慧方案
    'ptclass',
    # 2管网检测信息
    'emrecord',
    # 缺陷识别
    'imgseg',
    # 缺陷修复
    'defect_repair',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'simpleui_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'simpleui_demo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
# 配置MySQL
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "medicalana_sys",  # noqa
#         "USER": "root",
#         "PASSWORD": "zty061127ag",
#         "HOST": "127.0.0.1",
#         "PORT": "3306",
#     },
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "pipedb",  # noqa
        "USER": "root",
        "PASSWORD": "root",
        "HOST": "127.0.0.1",
        "PORT": "3306",
    },
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
# LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'ja'


TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
     os.path.join(BASE_DIR, "static"),
 ]
# 开发阶段可空，生产环境按需设置
STATIC_ROOT = ""

# simpleui 设置

# 首页配置
# SIMPLEUI_HOME_PAGE = 'https://www.baidu.com'
# 首页标题
# SIMPLEUI_HOME_TITLE = '百度一下你就知道'
# 首页图标,支持element-ui的图标和fontawesome的图标
# SIMPLEUI_HOME_ICON = 'el-icon-date'

# 设置simpleui 点击首页图标跳转的地址
# SIMPLEUI_INDEX = 'https://www.88cto.com'

# 首页显示服务器、python、django、simpleui相关信息
SIMPLEUI_HOME_INFO = False

# 首页显示快速操作
# SIMPLEUI_HOME_QUICK = False

# 首页显示最近动作
# SIMPLEUI_HOME_ACTION = False

# 自定义SIMPLEUI的Logo 换成自己的
SIMPLEUI_LOGO = '/static/logo/管网logo.png'

# 登录页粒子动画，默认开启，False关闭
SIMPLEUI_LOGIN_PARTICLES = False

# 让simpleui 不要收集相关信息
SIMPLEUI_ANALYSIS = True

# 自定义simpleui 菜单
SIMPLEUI_CONFIG = {
    # 在自定义菜单的基础上保留系统模块
    'system_keep': False,
    'menus': [{
        'name': '管网检测信息',
        'app_label': 'emrecord',
        'app_url': '/emrecord/',
        'has_module_perms': True,
        'models': [{
            'name': '管段信息',
            'object_name': 'Patient',
            'perms': {
                'add': True,
                'change': True,
                'delete': True,
                'view': True
            },
            'url': '/emrecord/patient/',
            'add_url': '/emrecord/patient/add/',
            'view_only': False
        }, {
            'name': '缺陷记录',
            'object_name': 'PatientRecord',
            'perms': {
                'add': True,
                'change': True,
                'delete': True,
                'view': True
            },
            'url': '/emrecord/patientrecord/',
            'add_url': '/emrecord/patientrecord/add/',
            'view_only': False
        }]
    }, {
        'name': '缺陷识别',
        'icon': 'far fa-chart-bar',
        'app_label': 'imgseg',
        'app_url': '/imgseg/',
        'has_module_perms': True,
        'models': [{
            'name': '图像处理',
            'object_name': 'Image',
            'perms': {
                'add': True,
                'change': True,
                'delete': True,
                'view': True
            },
            'url': '/imgseg/image/',
            'add_url': '/imgseg/image/add/',
            'view_only': False
        }]
    }, {
        'name': '缺陷分类',
        'app_label': 'imgclass',
        'app_url': '/imgclass/',
        'has_module_perms': True,
        'models': [{
            'name': '图像辅助判断',
            'icon': 'fas fa-wrench',
            'object_name': 'ImgClass',
            'perms': {
                'add': True,
                'change': True,
                'delete': True,
                'view': True
            },
            'url': '/imgclass/imgclass/',
            'add_url': '/imgclass/imgclass/add/',
            'view_only': False
        },{
            'name': '文本辅助判断',
            'icon': 'fas fa-wrench',
            'object_name': 'TextClass',
            'perms': {
                'add': True,
                'change': True,
                'delete': True,
                'view': True
            },
            'url': '/imgclass/textclass/',
            'add_url': '/imgclass/textclass/add/',
            'view_only': False
        }]
    }, {
        'name': '缺陷修复',
        'icon': 'fas fa-tools',
        'app_label': 'defect_repair',
        'app_url': '/defect_repair/',
        'has_module_perms': True,
        'models': [{
            'name': '缺陷录入',
            'object_name': 'DefectInfo',
            'perms': {
                'add': True,
                'change': True,
                'delete': True,
                'view': True
            },
            'url': '/defect_repair/defectinfo/',
            'add_url': '/defect_repair/defectinfo/add/',
            'view_only': False
        }, {
            'name': '修复建议',
            'object_name': 'RepairSuggestion',
            'perms': {
                'add': True,
                'change': True,
                'delete': True,
                'view': True
            },
            'url': '/defect_repair/repairsuggestion/',
            'add_url': '/defect_repair/repairsuggestion/add/',
            'view_only': False
        }]
    }, {
        'name': '智慧方案',
        'icon': 'fas fa-book-open',
        'app_label': 'ptclass',
        'app_url': '/ptclass/',
        'has_module_perms': True,
        'models': [{
            'name': '修复建议',
            'object_name': 'PtClass',
            'perms': {
                'add': True,
                'change': True,
                'delete': True,
                'view': True
            },
            'url': '/ptclass/ptclass/',
            'add_url': '/ptclass/ptclass/add/',
            'view_only': False
        }]
    }, {
        'name': '认证和授权',
        'icon': 'fas fa-user-tie',
        'app_label': 'auth',
        'app_url': '/auth/',
        'has_module_perms': True,
        'models': [{
            'name': '用户',
            'object_name': 'User',
            'perms': {
                'add': True,
                'change': True,
                'delete': True,
                'view': True
            },
            'url': '/auth/user/',
            'add_url': '/auth/user/add/',
            'view_only': False
        }, {
            'name': '组',
            'object_name': 'Group',
            'perms': {
                'add': True,
                'change': True,
                'delete': True,
                'view': True
            },
            'url': '/auth/group/',
            'add_url': '/auth/group/add/',
            'view_only': False
        }]
    }]
}

# 是否显示默认图标，默认=True
SIMPLEUI_DEFAULT_ICON = False

# 图标设置，图标参考：
SIMPLEUI_ICON = {
    # '系统管理': 'fab fa-apple',
    # '员工管理': 'fas fa-user-tie',
    '缺陷分类': 'fas fa-camera-retro',
    # '辅助判断': 'fas fa-wrench',
    '缺陷识别': 'far fa-chart-bar',
    '智慧方案': 'fas fa-book-open',
    # '修复建议': 'fas fa-tags',
    '电子报告': 'far fa-user',
    # '医嘱': 'fas fa-user-md'
}

# 指定simpleui 是否以脱机模式加载静态资源，为True的时候将默认从本地读取所有资源，即使没有联网一样可以。适合内网项目
# 不填该项或者为False的时候，默认从第三方的cdn获取

SIMPLEUI_STATIC_OFFLINE = True

# 设置上传目录
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# 设置前缀
MEDIA_URL = ''

# 默认主题 设置
SIMPLEUI_DEFAULT_THEME = 'ant.design.css'

# django 3.2要配置
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
