# Generated by Django 3.2.4 on 2023-04-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgclass',
            name='state',
            field=models.IntegerField(choices=[(0, '图像待诊断......'), (1, '立即修复'), (2, '尽快修复'), (3, '无需修复')], default=0, editable=False, help_text='初步分类', verbose_name='初步诊断结果'),
        ),
    ]
