# Generated by Django 3.2.4 on 2025-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgclass', '0002_alter_imgclass_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入工点名称', max_length=15, verbose_name='工点名称')),
                ('pipe_type', models.CharField(default='YC', help_text='请输入管段类型', max_length=50, verbose_name='管段类型')),
                ('pipe_material', models.CharField(help_text='请输入管段材质', max_length=100, verbose_name='管段材质')),
                ('pipe_diameter', models.FloatField(help_text='请输入管段直径', verbose_name='管段直径(mm)')),
                ('pipe_length', models.FloatField(help_text='请输入管段长度', verbose_name='管段长度(m)')),
                ('inspection_length', models.FloatField(help_text='请输入检测长度', verbose_name='检测长度(m)')),
                ('start_depth', models.FloatField(help_text='请输入起点埋深', verbose_name='起点埋深(m)')),
                ('end_depth', models.FloatField(help_text='请输入终点埋深', verbose_name='终点埋深(m)')),
                ('defect_location', models.CharField(help_text='请输入缺陷位置', max_length=100, verbose_name='缺陷位置')),
                ('defect_type', models.CharField(help_text='请输入缺陷类型', max_length=100, verbose_name='缺陷类型')),
                ('inspection_description', models.TextField(help_text='请输入检测描述', verbose_name='检测描述')),
                ('state', models.IntegerField(choices=[(0, '待判断......'), (1, '沉积'), (2, '破裂'), (3, '错口'), (4, '脱节')], default=0, editable=False, help_text='缺陷分类', verbose_name='缺陷类别')),
            ],
            options={
                'verbose_name': '缺陷分类',
                'verbose_name_plural': '文本缺陷分类',
                'db_table': 'text_class',
            },
        ),
        migrations.AlterModelOptions(
            name='imgclass',
            options={'verbose_name': '缺陷分类', 'verbose_name_plural': '图像辅助判断'},
        ),
        migrations.AlterField(
            model_name='imgclass',
            name='state',
            field=models.IntegerField(choices=[(0, '图像待判断......'), (1, '沉积'), (2, '破裂'), (3, '错口')], default=0, editable=False, help_text='初步分类', verbose_name='初步判断结果'),
        ),
    ]
